### ISSUE TITLE
Compile error on OS X with Xamarin

### ISSUE THREAD

**Issue by jbeeko** [tpetricek/Dojo-Suave-FsHome#1]
FYI - Working through the Suave.io dojo on OS X using Xamarin Studio. The snipped below is as provided in your latest commit (792fce76ed6bf3c00da53481d0285eb697a15853) but does not compile because defaultArg() expects a string option type but queryParam returns a choice type.

This does not occur with VisualStudio 2013. I'm pretty new to f# so don't really know if this indicates an issue with the Dojo material, a issue with the compiler on OS X, an issue with Mone or something else. 

```
    let waitAndReturn : WebPart = fun ctx -> async {
      let time = "1000" |> defaultArg (ctx.request.queryParam "time")
      do! Async.Sleep(int time)
      return! ctx |> OK (sprintf "Waited %d ms" (int time)) }
```

![screen shot 2015-05-22 at 11 13 07 am](https://cloud.githubusercontent.com/assets/4968704/7768501/9089d9fc-0073-11e5-9e6b-c3e96c16bfe6.png)

**Comment by tpetricek** [comment]
You are correct - there was a breaking change in Suave. I just updated to the latest version & fixed the issue, so it should work now.

**Comment by tpetricek** [comment]
BTW: I actually changed the example a bit - but you can get the original behavior using:

```
 match ctx.request.queryParam "time" with
 | Choice1Of2 value -> value
 | Choice2Of2 error -> "1000"
```
